# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['python/main.py'],
    pathex=[],
    binaries=[],
    datas=[('python/togcode/printers', 'dist'), ('python/twilight_colormap.png', '.')],
    hiddenimports=[
        'togcode.printers.Anet_A8', 
        'togcode.printers.Anycubic_Mega_Zero',
        'togcode.printers.Artillery_SW_X1', 
        'togcode.printers.BambuLab_X1C',
        'togcode.printers.Creality_K1_Max', 
        'togcode.printers.CR10',
        'togcode.printers.CR10S_Pro', 
        'togcode.printers.CR10_S5', 
        'togcode.printers.E3D_Toolchanger', 
        'togcode.printers.Ender2', 
        'togcode.printers.Ender3', 
        'togcode.printers.Flsun_SR', 
        'togcode.printers.Kingroon_P3', 
        'togcode.printers.Kywoo3D_Tycoon'
        'togcode.printers.Lutum_4.6', 
        'togcode.printers.Micro_Delta_Rework', 
        'togcode.printers.Monoprice_select_mini_v2', 
        'togcode.printers.Pharaoh_xd', 
        'togcode.printers.Prusa_MK2S', 
        'togcode.printers.Prusa_MK3S', 
        'togcode.printers.Replicator2', 
        'togcode.printers.Replicator2x', 
        'togcode.printers.Snapmaker', 
        'togcode.printers.Strateo3D', 
        'togcode.printers.Ultimaker2', 
        'togcode.printers.Ultimaker3', 
        'togcode.printers.UltimakerS3', 
        'togcode.printers.UltimakerS5', 
        'togcode.printers.UltimakerS7', 
        'togcode.printers.Voron_V0', 
        'togcode.printers.Volumic_Stream30_Pro_MK2', 
        'togcode.printers.Wasp_2040_Pro',
        'twilight_colormap.png',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
